// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/accounts": {
            "post": {
                "description": "Creates a new bank account for a given client ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Accounts"
                ],
                "summary": "Creates a new account",
                "parameters": [
                    {
                        "description": "Client ID for the new account",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/clientdto.CreateAccountRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Created account successfully",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "account": {
                                    "$ref": "#/definitions/clientdto.AccountDto"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request - Invalid input or client ID",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/accounts/completeNewUserRegistration": {
            "post": {
                "description": "Finalizes the registration process for a new user, including Keycloak user creation and account service completion.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Accounts"
                ],
                "summary": "Completes new user registration",
                "parameters": [
                    {
                        "description": "Registration details for the new user",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/clientdto.CompleteClientRegistrationBankAccountRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "User registration completed successfully\" // 201 for creation",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request - Invalid input",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/accounts/{client_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Receives the client_id to fetch all the accounts from a Client",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Accounts"
                ],
                "summary": "Returns client accounts",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "The ID of the client whose accounts want to be fetched",
                        "name": "client_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved client accounts",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/clientdto.AccountDto"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request - Invalid client ID",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/authorization/login": {
            "post": {
                "description": "Authorizes an User by using its credentials (Identification -Spanish NID- and password)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authorization"
                ],
                "summary": "User Authorization",
                "parameters": [
                    {
                        "description": "Credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/clientdto.AuthorizationRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "A session ID to use the same token",
                        "name": "session-id",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved User authorization",
                        "schema": {
                            "$ref": "#/definitions/api_keycloak.TokenResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request - Invalid client ID",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/clients": {
            "post": {
                "description": "Recibe los datos de un cliente y lo registra en el sistema.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Clients"
                ],
                "summary": "Crea un nuevo cliente",
                "parameters": [
                    {
                        "description": "Datos del cliente para crear",
                        "name": "client",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/clientdto.CreateClientRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Cliente creado exitosamente",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Solicitud inválida",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api_keycloak.TokenResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "expires_in": {
                    "type": "integer"
                },
                "not-before-policy": {
                    "type": "integer"
                },
                "refresh_expires_in": {
                    "type": "integer"
                },
                "refresh_token": {
                    "type": "string"
                },
                "scope": {
                    "type": "string"
                },
                "session_state": {
                    "type": "string"
                },
                "token_type": {
                    "type": "string"
                }
            }
        },
        "clientdto.AccountDto": {
            "type": "object",
            "required": [
                "created_date",
                "updated_date"
            ],
            "properties": {
                "account_number": {
                    "type": "string"
                },
                "balance": {
                    "type": "number"
                },
                "client_id": {
                    "description": "From Keycloak",
                    "type": "integer"
                },
                "created_date": {
                    "description": "ISO 8601 date (YYYY-MM-DD HH:mm:ss)",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "updated_date": {
                    "description": "ISO 8601 date (YYYY-MM-DD HH:mm:ss)",
                    "type": "string"
                }
            }
        },
        "clientdto.AuthorizationRequest": {
            "type": "object",
            "required": [
                "password",
                "user"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "user": {
                    "type": "string"
                }
            }
        },
        "clientdto.CompleteClientRegistrationBankAccountRequest": {
            "type": "object",
            "required": [
                "identification",
                "otp",
                "pin"
            ],
            "properties": {
                "identification": {
                    "type": "string"
                },
                "otp": {
                    "type": "string"
                },
                "pin": {
                    "type": "string"
                }
            }
        },
        "clientdto.CreateAccountRequest": {
            "type": "object",
            "properties": {
                "client_id": {
                    "type": "integer"
                }
            }
        },
        "clientdto.CreateClientRequest": {
            "type": "object",
            "required": [
                "address",
                "city",
                "date_of_birth",
                "email",
                "identification",
                "name",
                "nationality",
                "province",
                "sex",
                "surname1",
                "telephone",
                "zip_code"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "date_of_birth": {
                    "description": "ISO 8601 date (YYYY-MM-DD)",
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "identification": {
                    "description": "e.g., passport, national ID",
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "nationality": {
                    "description": "e.g., ISO 3166-1 alpha-2 code",
                    "type": "string"
                },
                "province": {
                    "type": "string"
                },
                "sex": {
                    "description": "M(ale), F(emale)",
                    "type": "string",
                    "enum": [
                        "M",
                        "F"
                    ]
                },
                "state": {
                    "description": "Optional, depending on country",
                    "type": "string"
                },
                "surname1": {
                    "type": "string"
                },
                "surname2": {
                    "description": "Optional, as not all have second surname",
                    "type": "string"
                },
                "tax_id": {
                    "description": "e.g., SSN, TIN",
                    "type": "string"
                },
                "telephone": {
                    "description": "Basic phone validation can be added",
                    "type": "string"
                },
                "zip_code": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "API Bank Clients",
	Description:      "Clients management of a bank system.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
